In [1]:
import os, json, numpy as np, matplotlib.pyplot as plt

# list files
for root, dirs, files in os.walk('/home/skanda/active_matter/data'):
    print(root, files[:5])

/home/skanda/active_matter/data []
/home/skanda/active_matter/data/test ['active_matter_L_10.0_zeta_11.0_alpha_-4.0.hdf5', 'active_matter_L_10.0_zeta_5.0_alpha_-3.0.hdf5', 'active_matter_L_10.0_zeta_11.0_alpha_-1.0.hdf5', 'active_matter_L_10.0_zeta_11.0_alpha_-3.0.hdf5', 'active_matter_L_10.0_zeta_1.0_alpha_-2.0.hdf5']
/home/skanda/active_matter/data/valid ['active_matter_L_10.0_zeta_11.0_alpha_-4.0.hdf5', 'active_matter_L_10.0_zeta_1.0_alpha_-3.0.hdf5', 'active_matter_L_10.0_zeta_3.0_alpha_-2.0.hdf5', 'active_matter_L_10.0_zeta_5.0_alpha_-1.0.hdf5', 'active_matter_L_10.0_zeta_13.0_alpha_-3.0.hdf5']
/home/skanda/active_matter/data/train ['active_matter_L_10.0_zeta_11.0_alpha_-4.0.hdf5', 'active_matter_L_10.0_zeta_5.0_alpha_-3.0.hdf5', 'active_matter_L_10.0_zeta_11.0_alpha_-1.0.hdf5', 'active_matter_L_10.0_zeta_17.0_alpha_-2.0.hdf5', 'active_matter_L_10.0_zeta_11.0_alpha_-3.0.hdf5']


In [2]:
import h5py
import numpy as np
import matplotlib.pyplot as plt

In [3]:
f = h5py.File("/home/skanda/active_matter/data/train/active_matter_L_10.0_zeta_11.0_alpha_-4.0.hdf5", "r")

def print_structure(name, obj):
    print(name, "|", type(obj))

f.visititems(print_structure)

boundary_conditions | <class 'h5py._hl.group.Group'>
boundary_conditions/x_periodic | <class 'h5py._hl.group.Group'>
boundary_conditions/x_periodic/mask | <class 'h5py._hl.dataset.Dataset'>
boundary_conditions/y_periodic | <class 'h5py._hl.group.Group'>
boundary_conditions/y_periodic/mask | <class 'h5py._hl.dataset.Dataset'>
dimensions | <class 'h5py._hl.group.Group'>
dimensions/time | <class 'h5py._hl.dataset.Dataset'>
dimensions/x | <class 'h5py._hl.dataset.Dataset'>
dimensions/y | <class 'h5py._hl.dataset.Dataset'>
scalars | <class 'h5py._hl.group.Group'>
scalars/L | <class 'h5py._hl.dataset.Dataset'>
scalars/alpha | <class 'h5py._hl.dataset.Dataset'>
scalars/zeta | <class 'h5py._hl.dataset.Dataset'>
t0_fields | <class 'h5py._hl.group.Group'>
t0_fields/concentration | <class 'h5py._hl.dataset.Dataset'>
t1_fields | <class 'h5py._hl.group.Group'>
t1_fields/velocity | <class 'h5py._hl.dataset.Dataset'>
t2_fields | <class 'h5py._hl.group.Group'>
t2_fields/D | <class 'h5py._hl.dataset.Da

In [11]:
import h5py

f = h5py.File("/home/skanda/active_matter/data/train/active_matter_L_10.0_zeta_9.0_alpha_-4.0.hdf5", "r")

def print_structure(name, obj):
    print(name, "|", type(obj))

f.visititems(print_structure)

def print_shapes(name, obj):
    if isinstance(obj, h5py.Dataset):
        print(f"{name:40s} | shape: {obj.shape}")

f.visititems(print_shapes)

boundary_conditions | <class 'h5py._hl.group.Group'>
boundary_conditions/x_periodic | <class 'h5py._hl.group.Group'>
boundary_conditions/x_periodic/mask | <class 'h5py._hl.dataset.Dataset'>
boundary_conditions/y_periodic | <class 'h5py._hl.group.Group'>
boundary_conditions/y_periodic/mask | <class 'h5py._hl.dataset.Dataset'>
dimensions | <class 'h5py._hl.group.Group'>
dimensions/time | <class 'h5py._hl.dataset.Dataset'>
dimensions/x | <class 'h5py._hl.dataset.Dataset'>
dimensions/y | <class 'h5py._hl.dataset.Dataset'>
scalars | <class 'h5py._hl.group.Group'>
scalars/L | <class 'h5py._hl.dataset.Dataset'>
scalars/alpha | <class 'h5py._hl.dataset.Dataset'>
scalars/zeta | <class 'h5py._hl.dataset.Dataset'>
t0_fields | <class 'h5py._hl.group.Group'>
t0_fields/concentration | <class 'h5py._hl.dataset.Dataset'>
t1_fields | <class 'h5py._hl.group.Group'>
t1_fields/velocity | <class 'h5py._hl.dataset.Dataset'>
t2_fields | <class 'h5py._hl.group.Group'>
t2_fields/D | <class 'h5py._hl.dataset.Da

In [7]:
import h5py
import numpy as np

f = h5py.File("/home/skanda/active_matter/data/train/active_matter_L_10.0_zeta_11.0_alpha_-4.0.hdf5", "r")

print("=" * 80)
print("SCALARS (single values):")
print("=" * 80)
print(f"L = {f['scalars/L'][()]}")
print(f"alpha = {f['scalars/alpha'][()]}")
print(f"zeta = {f['scalars/zeta'][()]}")

print("\n" + "=" * 80)
print("DIMENSIONS (first 5 values):")
print("=" * 80)
print(f"time: {f['dimensions/time'][:5]}")
print(f"x: {f['dimensions/x'][:5]}")
print(f"y: {f['dimensions/y'][:5]}")

print("\n" + "=" * 80)
print("CONCENTRATION at t=0 (first 5x5 region):")
print("=" * 80)
conc = f['t0_fields/concentration'][0, 0, :5, :5]
print(conc)

print("\n" + "=" * 80)
print("VELOCITY at t=0 (first 3x3, both components):")
print("=" * 80)
vel = f['t1_fields/velocity'][0, 0, :3, :3, :]
print(vel)

print("\n" + "=" * 80)
print("D tensor at t=0 (first element, 2x2 tensor):")
print("=" * 80)
d = f['t2_fields/D'][0, 0, 0, 0, :, :]
print(d)

f.close()

SCALARS (single values):
L = 10.0
alpha = -4.0
zeta = 11.0

DIMENSIONS (first 5 values):
time: [0.   0.25 0.5  0.75 1.  ]
x: [0.         0.03921569 0.07843138 0.11764706 0.15686275]
y: [0.         0.03921569 0.07843138 0.11764706 0.15686275]

CONCENTRATION at t=0 (first 5x5 region):
[[0.9945734  0.99315816 0.9915234  0.98972887 0.98784167]
 [0.99429804 0.9930725  0.99165064 0.9900854  0.9884365 ]
 [0.9940421  0.9930519  0.99189144 0.9906054  0.98924434]
 [0.99383426 0.9931158  0.9922553  0.9912876  0.99025285]
 [0.99370474 0.99328375 0.9927499  0.99212754 0.9914452 ]]

VELOCITY at t=0 (first 3x3, both components):
[[[-0.00283017  0.00237428]
  [-0.00135119  0.00332203]
  [ 0.00014077  0.00424119]]

 [[-0.00375153  0.00260698]
  [-0.00226039  0.00349269]
  [-0.00072735  0.00435368]]

 [[-0.00460358  0.00275465]
  [-0.00310356  0.00356695]
  [-0.00153436  0.00435889]]]

D tensor at t=0 (first element, 2x2 tensor):
[[0.48074982 0.00583462]
 [0.00583462 0.51382357]]


In [2]:
import h5py
import os
from pathlib import Path

def count_total_samples(data_dir, num_frames=16, stride=1):
    """
    Calculate total number of training samples from raw HDF5 files.
    
    Args:
        data_dir: Path to directory containing HDF5 files
        num_frames: Frames per sample (context + target combined)
        stride: Sliding window stride
    
    Returns:
        Total samples and breakdown per file
    """
    hdf5_files = list(Path(data_dir).glob("*.hdf5")) + list(Path(data_dir).glob("*.h5"))
    
    if not hdf5_files:
        print(f"No HDF5 files found in {data_dir}")
        return
    
    total_samples = 0
    samples_per_file = {}
    
    for file_path in hdf5_files:
        try:
            with h5py.File(file_path, "r") as f:
                # Get number of timesteps (try different possible keys)
                if 'dimensions/time' in f:
                    num_timesteps = f['dimensions/time'].shape[0]
                elif 'time' in f:
                    num_timesteps = f['time'].shape[0]
                else:
                    # Fallback: check first field's time dimension
                    first_field = None
                    for key in f.keys():
                        if isinstance(f[key], h5py.Group):
                            for subkey in f[key].keys():
                                if isinstance(f[key][subkey], h5py.Dataset):
                                    first_field = f[key][subkey]
                                    break
                    
                    if first_field is None:
                        print(f"Could not determine timesteps in {file_path.name}")
                        continue
                    
                    num_timesteps = first_field.shape[1] if len(first_field.shape) > 1 else first_field.shape[0]
                
                # Calculate samples from this file
                # sliding window: [t0:t0+num_frames), [t0+stride:t0+stride+num_frames), ...
                num_samples = max(0, (num_timesteps - num_frames) // stride + 1)
                
                samples_per_file[file_path.name] = {
                    'timesteps': num_timesteps,
                    'samples': num_samples
                }
                total_samples += num_samples
                
        except Exception as e:
            print(f"Error processing {file_path.name}: {e}")
    
    # Print results
    print(f"\n{'File':<60} | {'Timesteps':<12} | {'Samples':<10}")
    print("=" * 85)
    for filename, info in sorted(samples_per_file.items()):
        print(f"{filename:<60} | {info['timesteps']:<12} | {info['samples']:<10}")
    
    print("=" * 85)
    print(f"Total files: {len(samples_per_file)}")
    print(f"Total samples: {total_samples}")
    print(f"(Config: num_frames={num_frames}, stride={stride})")
    
    return total_samples, samples_per_file


# Usage
if __name__ == "__main__":
    # Adjust these paths
    train_dir = "/home/skanda/active_matter/data/train"
    val_dir = "/home/skanda/active_matter/data/valid"
    test_dir = "/home/skanda/active_matter/data/test"
    
    print("TRAINING SET")
    train_total, _ = count_total_samples(train_dir, num_frames=8, stride=1)
    
    print("\n\nVALIDATION SET")
    val_total, _ = count_total_samples(val_dir, num_frames=8, stride=1)
    
    print("\n\nTEST SET")
    test_total, _ = count_total_samples(test_dir, num_frames=8, stride=1)
    
    print("\n\nSUMMARY")
    print(f"Train: {train_total}")
    print(f"Val: {val_total}")
    print(f"Test: {test_total}")
    print(f"Total: {train_total + val_total + test_total}")

TRAINING SET

File                                                         | Timesteps    | Samples   
active_matter_L_10.0_zeta_1.0_alpha_-1.0.hdf5                | 81           | 74        
active_matter_L_10.0_zeta_1.0_alpha_-2.0.hdf5                | 81           | 74        
active_matter_L_10.0_zeta_1.0_alpha_-3.0.hdf5                | 81           | 74        
active_matter_L_10.0_zeta_1.0_alpha_-4.0.hdf5                | 81           | 74        
active_matter_L_10.0_zeta_1.0_alpha_-5.0.hdf5                | 81           | 74        
active_matter_L_10.0_zeta_11.0_alpha_-1.0.hdf5               | 81           | 74        
active_matter_L_10.0_zeta_11.0_alpha_-2.0.hdf5               | 81           | 74        
active_matter_L_10.0_zeta_11.0_alpha_-3.0.hdf5               | 81           | 74        
active_matter_L_10.0_zeta_11.0_alpha_-4.0.hdf5               | 81           | 74        
active_matter_L_10.0_zeta_11.0_alpha_-5.0.hdf5               | 81           | 74        
active_

In [4]:
import h5py
import os
from pathlib import Path

def count_total_samples(data_dir, num_frames=16, stride=1):
    """Calculate total samples from raw HDF5 files."""
    hdf5_files = list(Path(data_dir).glob("*.hdf5")) + list(Path(data_dir).glob("*.h5"))
    
    if not hdf5_files:
        print(f"No HDF5 files found in {data_dir}")
        return 0, {}
    
    total_samples = 0
    samples_per_file = {}
    
    for file_path in sorted(hdf5_files):
        try:
            with h5py.File(file_path, "r") as f:
                # Get timesteps
                if 'dimensions/time' in f:
                    num_timesteps = f['dimensions/time'].shape[0]
                else:
                    continue
                
                # Calculate samples: (T - F) / stride + 1
                num_samples = max(0, (num_timesteps - num_frames) // stride + 1)
                
                samples_per_file[file_path.name] = {
                    'timesteps': num_timesteps,
                    'samples': num_samples
                }
                total_samples += num_samples
                
        except Exception as e:
            print(f"Error: {file_path.name}: {e}")
    
    return total_samples, samples_per_file

def print_results(split_name, total_samples, samples_per_file):
    """Print formatted results."""
    print(f"\n{'='*85}")
    print(f"{split_name.upper()}")
    print(f"{'='*85}")
    print(f"{'File':<60} | {'T':<4} | {'Samples':<8}")
    print("-"*85)
    
    for filename in sorted(samples_per_file.keys()):
        info = samples_per_file[filename]
        print(f"{filename:<60} | {info['timesteps']:<4} | {info['samples']:<8}")
    
    print("-"*85)
    print(f"Total files: {len(samples_per_file)}")
    print(f"Total samples: {total_samples}")

if __name__ == "__main__":
    train_dir = "/home/skanda/active_matter/data/train"
    val_dir = "/home/skanda/active_matter/data/valid"
    test_dir = "/home/skanda/active_matter/data/test"
    
    num_frames = 16
    
    print(f"\n\n{'#'*85}")
    print(f"CALCULATING WITH num_frames={num_frames}")
    print(f"{'#'*85}")
    
    train_total, train_files = count_total_samples(train_dir, num_frames=num_frames, stride=1)
    val_total, val_files = count_total_samples(val_dir, num_frames=num_frames, stride=1)
    test_total, test_files = count_total_samples(test_dir, num_frames=num_frames, stride=1)
    
    print_results("Training", train_total, train_files)
    print_results("Validation", val_total, val_files)
    print_results("Test", test_total, test_files)
    
    print(f"\n{'='*85}")
    print("FINAL SUMMARY")
    print(f"{'='*85}")
    print(f"Train:   {train_total:>8} samples")
    print(f"Val:     {val_total:>8} samples")
    print(f"Test:    {test_total:>8} samples")
    print(f"Total:   {train_total + val_total + test_total:>8} samples")
    print(f"\nExpected: 8750 train, 1200 val, 1300 test = 11250 total")
    print(f"Match: {'✓' if abs(train_total - 8750) < 100 else '✗'}")



#####################################################################################
CALCULATING WITH num_frames=16
#####################################################################################

TRAINING
File                                                         | T    | Samples 
-------------------------------------------------------------------------------------
active_matter_L_10.0_zeta_1.0_alpha_-1.0.hdf5                | 81   | 66      
active_matter_L_10.0_zeta_1.0_alpha_-2.0.hdf5                | 81   | 66      
active_matter_L_10.0_zeta_1.0_alpha_-3.0.hdf5                | 81   | 66      
active_matter_L_10.0_zeta_1.0_alpha_-4.0.hdf5                | 81   | 66      
active_matter_L_10.0_zeta_1.0_alpha_-5.0.hdf5                | 81   | 66      
active_matter_L_10.0_zeta_11.0_alpha_-1.0.hdf5               | 81   | 66      
active_matter_L_10.0_zeta_11.0_alpha_-2.0.hdf5               | 81   | 66      
active_matter_L_10.0_zeta_11.0_alpha_-3.0.hdf5               | 81  

In [14]:
import os
import h5py
from glob import glob

train_dir = "/home/skanda/active_matter/data/train"
val_dir = "/home/skanda/active_matter/data/valid"
test_dir = "/home/skanda/active_matter/data/test"

from pathlib import Path
import h5py

F = 16
stride = 1

def count_samples(split_dir):
    paths = list(Path(split_dir).rglob("*.h5")) + list(Path(split_dir).rglob("*.hdf5"))

    print("Found files:", len(paths))

    total = 0

    for path in paths:
        with h5py.File(path, "r") as f:
            N, T, H, W = f["t0_fields/concentration"].shape
            total += N * max(0, (T - 2*F)//stride + 1)

    print("Total samples:", total)
    return total

count_samples(train_dir)
count_samples(val_dir)
count_samples(test_dir)

Found files: 45
Total samples: 8750
Found files: 16
Total samples: 1200
Found files: 21
Total samples: 1300


1300